name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@d96bc962e61b3049ce8128d03d57a1144fa96539 # main
      - uses: DeterminateSystems/magic-nix-cache-action@cec65ff6f104850203b152861d3f9e5f1747885d # main

      - name: Restore Cargo cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('Cargo.lock', 'flake.lock', 'rust-toolchain.toml') }}
          restore-keys: cargo-

      - name: Format
        run: nix develop --command cargo fmt --check

      - name: Clippy
        run: nix develop --command cargo clippy --locked --workspace --all-targets -- -D warnings

      - name: Test
        run: nix develop --command cargo nextest run --locked --workspace

      - name: Save Cargo cache
        if: github.ref == 'refs/heads/main'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('Cargo.lock', 'flake.lock', 'rust-toolchain.toml') }}
